from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import RVTvInfo
from django import forms
from org.models import Org


class UploadFileForm(forms.Form):
    file = forms.FileField(
        label='Select a file',
        help_text='Upload a valid single CSV generated by RVTOOLS'
    )


class RVTDataForm(ModelForm):
    class Meta:
        model = RVTvInfo
        exclude = ('rvt_vi_user','rvt_vi_batch',)


# raise ValidationError("Invalid Something") -


class OrgForm(ModelForm):
    class Meta:
        model = Org  #.objects.filter(rvt_vi_user=User)
        fields = ('org_name',)
