# Generated by Django 2.0.2 on 2019-11-21 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assess_name', models.CharField(max_length=300, verbose_name='assess_name')),
                ('load_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('assess_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assess_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=300, verbose_name='Name')),
                ('org_contact', models.CharField(max_length=300, verbose_name='Contact')),
                ('org_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('load_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('org_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='assess_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assess_org', to='org.Org'),
        ),
    ]
